"""
Django settings for flight_log app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/fr/3.2/ref/applications/
"""

from django.apps import AppConfig


class FlightLogConfig(AppConfig):
    """flight_log app configuration"""

    default_auto_field = "django.db.models.BigAutoField"
    name = "flight_log"
