# Generated by Django 3.2.9 on 2021-11-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='questions_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcm.questionsset'),
        ),
    ]
