# Generated by Django 3.2.9 on 2021-11-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
        ('qcm', '0003_auto_20211118_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='lesson',
            field=models.ManyToManyField(to='user_data.Lesson'),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_data.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
