"""
Django settings for main app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/fr/3.2/ref/applications/
"""

from django.apps import AppConfig
from django.contrib.admin.apps import AdminConfig


class MainConfig(AppConfig):
    """main app configuration"""

    default_auto_field = "django.db.models.BigAutoField"
    name = "main"


class MainAdminConfig(AdminConfig):
    """main admin configuration"""

    default_site = "main.admin_site.EraAdminSite"
