"""
Django views for main app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/http/views/
"""

from django.shortcuts import render


def index_view(request):
    """home page view"""
    return render(request, "main/index.html", {})
