"""
Django settings for qcm app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/fr/3.2/ref/applications/
"""

from django.apps import AppConfig
from django.contrib.admin.apps import AdminConfig


class QcmConfig(AppConfig):
    """qcm app configuration"""

    default_auto_field = "django.db.models.BigAutoField"
    name = "qcm"


class QcmAdminConfig(AdminConfig):
    """qcm admin configuration"""

    default_site = "qcm.admin.QcmAdminSite"
