"""
Django views for qcm app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/http/views/
"""

from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Branch, Choice, Question


class IndexView(generic.ListView):
    """generic view of index"""

    template_name = "qcm/index.html"
    context_object_name = "branch_list"

    def get_queryset(self):
        """Return all published questions."""
        return Branch.objects.order_by("branch_name")


class DetailView(generic.ListView):
    """generic view of branch question"""

    template_name = "qcm/detail_branch.html"
    context_object_name = "question_list"


#    def get_queryset(self):
#        """Return all question linked to a branch"""
#        return


def detail_question(request, question_id):
    """view of detailed question"""
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "qcm/detail_question.html", {"question": question})


class ResultsView(generic.DetailView):
    """generic view of results question"""

    model = Question
    template_name = "qcm/results.html"


def answer(request, question_id):
    """answering question view"""
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.GET["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question answering form.
        return render(
            request,
            "qcm/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        return render(
            request,
            "qcm/results.html",
            {"question": question, "given_answer": selected_choice},
        )
