"""
Django tests for qcm app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/testing/
"""

from .test_branch import BranchModelTest
from .test_choice import ChoiceModelTest
from .test_question import QuestionModelTest
from .test_questions_subset import QuestionsSubsetModelTest
from .test_training import TrainingModelTest
