"""
Django tests for question in qcm app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/testing/
"""


from django.test import TestCase

from ..models import Question
from .test_shortcuts import create_question


class QuestionModelTest(TestCase):
    """class to test the Question model"""

    def test_create_question(self):
        """test a question creation"""
        question_text = "empty question"
        question = create_question(question_text)
        questions = Question.objects.all()
        self.assertQuerysetEqual(questions, [question])
