"""
Django tests for training in qcm app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/testing/
"""

from django.test import TestCase

from user_data.tests import create_student

from ..models import Training
from .test_shortcuts import create_branch_training, create_questions_subset_training


class TrainingModelTest(TestCase):
    """class to test the Training model"""

    def test_create_questions_subset_training(self):
        """test a training creation"""
        student = create_student(username="test")
        training = create_questions_subset_training(user=student)
        trainings = Training.objects.all()
        self.assertQuerysetEqual(trainings, [training])

    def test_create_branch_training(self):
        """test a training creation"""
        student = create_student(username="test")
        training = create_branch_training(user=student)
        trainings = Training.objects.all()
        self.assertQuerysetEqual(trainings, [training])
