# Generated by Django 3.2.9 on 2021-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erauser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
