# Generated by Django 3.2.9 on 2021-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_erauser_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='erauser',
            name='is_beta_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erauser',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erauser',
            name='is_pilot',
            field=models.BooleanField(default=True),
        ),
    ]
