"""
Django settings for user_data app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/fr/3.2/ref/applications/
"""

from django.apps import AppConfig


class UserDataConfig(AppConfig):
    """user_data app configuration"""

    default_auto_field = "django.db.models.BigAutoField"
    name = "user_data"
