"""
Django views for user_data app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/http/views/
"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from .forms import LessonCreationForm, LessonJoinForm, RegisterForm
from .models import Lesson
from .shortcuts import (
    check_user_personnal,
    manage_instructor_form,
    manage_personnal_form,
)


class IndexView(generic.ListView):
    """display lesson list"""

    template_name = "user_data/index.html"
    context_object_name = "lesson_list"

    def get_queryset(self):
        """return user linked lesson"""

        user = self.request.user
        if user.is_staff:
            return Lesson.objects.all().order_by("name")
        if not user.is_authenticated or (
            not user.is_student and not user.is_instructor
        ):
            return None

        lessons = user.student.lessons.all().order_by("name")
        return lessons


def register_view(request):
    """register view"""

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse("login"))

    else:
        form = RegisterForm()

    return render(request, "user_data/register.html", {"form": form})


@login_required
def create_lesson_view(request):
    """view to create a new lesson"""

    try:
        (instructor, lesson_form) = manage_instructor_form(
            request, form=LessonCreationForm
        )
        if lesson_form.is_valid():
            lesson = lesson_form.save()

            instructor.teaching.add(lesson)
            instructor.lessons.add(lesson)

            return HttpResponseRedirect(
                reverse(
                    "user_data:detail_lesson",
                    args=(lesson.id,),
                )
            )
    except ValidationError:
        lesson_form.clean()

    return render(request, "user_data/create_lesson.html", {"form": lesson_form})


class DetailLessonView(UserPassesTestMixin, generic.DetailView):
    """view lesson"""

    def test_func(self):
        """test if user is either staff or authenticated right personnal"""
        user = self.request.user
        if user.is_staff:
            return True
        student = check_user_personnal(self.request)
        if student is None:
            return False

        lesson = self.get_object()

        return student.lessons.filter(id=lesson.id).exists()

    model = Lesson
    template_name = "user_data/detail_lesson.html"


@login_required
def joint_lesson_view(request):
    """view to join an existing lesson"""

    try:
        (personnal, lesson_form) = manage_personnal_form(request, form=LessonJoinForm)
        if lesson_form.is_valid():
            lesson = lesson_form.validate_lesson(personnal)

            if lesson is not None:
                if not lesson.can_join:
                    raise ValidationError("You are not allowed to join this lesson.")

                personnal.lessons.add(lesson)
                return HttpResponseRedirect(
                    reverse(
                        "user_data:detail_lesson",
                        args=(lesson.id,),
                    )
                )
    except (ObjectDoesNotExist, ValidationError):
        lesson_form.clean()

    return render(request, "user_data/join_lesson.html", {"form": lesson_form})
