"""
Django views for user_data app.

Generated by 'manage.py startapp' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/http/views/
"""

from .lesson_view import (
    DetailLessonView,
    IndexView,
    create_lesson_view,
    join_lesson_view,
)
from .user_view import register_view
