# Generated by Django 3.2.9 on 2021-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='teaching',
            field=models.ManyToManyField(blank=True, to='user_data.Lesson'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='user_data.Lesson'),
        ),
    ]
