# Generated by Django 3.2.9 on 2021-11-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_lesson_id'),
        ('user_data', '0002_auto_20211126_1901'),
    ]

    operations = [
    ]
